window.JUNGMINI_WORKS = [
  {
    "id": "awskrug-seoul-summit-2026",
    "title": "AWSKRUG Seoul Summit 2026",
    "year": "2026",
    "category": "Event / Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design used for AWSKRUG Seoul Summit 2026.",
    "image": "./images/thumbs/awskrug-seoul-summit-2026.png",
    "pdf": "./files/awskrug sticker_seoul sumit_2026.pdf",
    "number": "No.001"
  },
  {
    "id": "ausg",
    "title": "AUSG",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/ausg.png",
    "pdf": "./files/ausg.pdf",
    "number": "No.002"
  },
  {
    "id": "busan",
    "title": "Busan",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/busan.png",
    "pdf": "./files/busan.pdf",
    "number": "No.003"
  },
  {
    "id": "frontend",
    "title": "Frontend",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/frontend.png",
    "pdf": "./files/frontend.pdf",
    "number": "No.004"
  },
  {
    "id": "kiro-and-grumi-love",
    "title": "Kiro and Grumi Love",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/kiro-and-grumi-love.png",
    "pdf": "./files/kiro and grumi love.pdf",
    "number": "No.005"
  },
  {
    "id": "women-in-cloud",
    "title": "Women in Cloud",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/women-in-cloud.png",
    "pdf": "./files/women in cloud.pdf",
    "number": "No.006"
  },
  {
    "id": "architecture",
    "title": "Architecture",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/architecture.png",
    "pdf": "./files/Architecture.pdf",
    "number": "No.007"
  },
  {
    "id": "devops",
    "title": "DevOps",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/devops.png",
    "pdf": "./files/DevOps.pdf",
    "number": "No.008"
  },
  {
    "id": "gametech",
    "title": "Gametech",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/gametech.png",
    "pdf": "./files/gametech.pdf",
    "number": "No.009"
  },
  {
    "id": "serverless",
    "title": "Serverless",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/severless.png",
    "pdf": "./files/severless.pdf",
    "number": "No.010"
  },
  {
    "id": "security",
    "title": "Security",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/security.png",
    "pdf": "./files/ security.pdf",
    "number": "No.011"
  },
  {
    "id": "data",
    "title": "Data",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/data.png",
    "pdf": "./files/data.pdf",
    "number": "No.012"
  },
  {
    "id": "kiro-ghost-gurumi",
    "title": "Kiro Ghost Gurumi",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/kiro-ghost-gurumi.png",
    "pdf": "./files/kiro ghost gurumi.pdf",
    "number": "No.013"
  },
  {
    "id": "iot",
    "title": "IoT",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/iot.png",
    "pdf": "./files/IOT.pdf",
    "number": "No.014"
  },
  {
    "id": "platform",
    "title": "Platform",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/platform.png",
    "pdf": "./files/plateform.pdf",
    "number": "No.015"
  },
  {
    "id": "magok",
    "title": "Magok",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/magok.png",
    "pdf": "./files/magok.pdf",
    "number": "No.016"
  },
  {
    "id": "inchun",
    "title": "Inchun",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/inchun.png",
    "pdf": "./files/inchun.pdf",
    "number": "No.017"
  },
  {
    "id": "euljiro",
    "title": "Euljiro",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/euljiro.png",
    "pdf": "./files/euljiro.pdf",
    "number": "No.018"
  },
  {
    "id": "certified",
    "title": "Certified",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/certified.png",
    "pdf": "./files/certified.pdf",
    "number": "No.019"
  },
  {
    "id": "guro",
    "title": "Guro",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/guro.png",
    "pdf": "./files/guro.pdf",
    "number": "No.020"
  },
  {
    "id": "container",
    "title": "Container",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/container.png",
    "pdf": "./files/container.pdf",
    "number": "No.021"
  },
  {
    "id": "beginner",
    "title": "Beginner",
    "year": "2026",
    "category": "Sticker",
    "format": "PDF, sticker design",
    "note": "Sticker design.",
    "image": "./images/thumbs/beginner.png",
    "pdf": "./files/beginner.pdf",
    "number": "No.022"
  },
  {
    "id": "personal-gemini-generated-image-5okxiy5okxiy5okx",
    "title": "Gemini Generated Image 5okxiy5okxiy5okx",
    "year": "2026",
    "category": "Personal Work",
    "format": "Image",
    "note": "Personal Work by Jungmini.",
    "image": "./images/personal/Gemini_Generated_Image_5okxiy5okxiy5okx.png",
    "pdf": "",
    "number": "No.023"
  },
  {
    "id": "personal-gemini-generated-image-h9m3mdh9m3mdh9m3",
    "title": "Gemini Generated Image H9m3mdh9m3mdh9m3",
    "year": "2026",
    "category": "Personal Work",
    "format": "Image",
    "note": "Personal Work by Jungmini.",
    "image": "./images/personal/Gemini_Generated_Image_h9m3mdh9m3mdh9m3.png",
    "pdf": "",
    "number": "No.024"
  }
];
